INSERT INTO lecture (title, lecturer, lecture_date, start_time, end_time, remaining_capacity, deleted_at, created_at, updated_at) VALUES('인공지능 기초', '김철수', '2024-12-25', '09:00:00', '11:00:00', 30, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),('고급 자바 프로그래밍', '이영희', '2024-12-25', '13:00:00', '15:00:00', 25, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),('웹 개발 기초', '박지훈', '2024-12-26', '10:00:00', '12:00:00', 30, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),('React.js 심화', '최지은', '2024-12-26', '14:00:00', '16:00:00', 30, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),('데이터베이스 기초', '김선영', '2024-12-27', '09:00:00', '11:00:00', 30, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),('클라우드 컴퓨팅', '이준호', '2024-12-27', '13:00:00', '15:00:00', 30, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('AI 응용', '박수정', '2024-12-28', '09:00:00', '11:00:00', 25, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),('안드로이드 앱 개발', '정현석', '2024-12-28', '13:00:00', '15:00:00', 30, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('빅데이터 분석', '김태호', '2024-12-29', '10:00:00', '12:00:00', 30, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('머신러닝 기초', '이상원', '2024-12-29', '14:00:00', '16:00:00', 25, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "user" (id, name, created_at, updated_at) VALUES (1, '홍길동1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (2, '홍길동2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (3, '홍길동3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (4, '홍길동4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (5, '홍길동5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (6, '홍길동6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (7, '홍길동7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (8, '홍길동8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (9, '홍길동9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (10, '홍길동10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (11, '홍길동11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (12, '홍길동12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (13, '홍길동13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (14, '홍길동14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (15, '홍길동15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (16, '홍길동16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (17, '홍길동17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (18, '홍길동18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (19, '홍길동19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (20, '홍길동20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (21, '홍길동21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (22, '홍길동22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (23, '홍길동23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (24, '홍길동24', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (25, '홍길동25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (26, '홍길동26', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (27, '홍길동27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (28, '홍길동28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (29, '홍길동29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (30, '홍길동30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (31, '홍길동31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (32, '홍길동32', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (33, '홍길동33', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (34, '홍길동34', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (35, '홍길동35', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (36, '홍길동36', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (37, '홍길동37', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (38, '홍길동38', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (39, '홍길동39', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "user" (id, name, created_at, updated_at) VALUES (40, '홍길동40', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO lecture_registration (lecture_id, user_id, deleted_at, created_at, updated_at) VALUES(1, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(4, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(5, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(6, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(7, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(8, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(9, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(10, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);